export default {
  userInfo: {
    id: '',
    updateAt: 0,
    name: '',
    mobile: '',
    email: '',
    loginAt: 0,
    status: '',
    role: '',
    department: '',
    position: '',
    extra: '',
    wechatOpenId: '',
    subscribed: false,
    unionid: '',
  },
  userState: 0,
  userAuth: 0,
  secretMobile: '未绑定',
}